name: ci
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "{{PY_VER}}"
      - run: { { INSTALL_CMD } }
      - run: { { VERIFY_CMD } }
