"""Default platform recognition rules (seed data).

每条规则 = (规则名, 匹配字段, 匹配方式, 模式, 目标平台); 依据常见平台发件
域名归纳, 供「加载默认规则」与首次启动种入使用。
"""

from __future__ import annotations

DEFAULT_PLATFORM_RULES: tuple[tuple[str, str, str, str, str], ...] = (
    ("GitHub", "domain", "contains", "github.com", "GitHub"),
    ("GitKraken", "domain", "contains", "gitkraken.com", "GitKraken"),
    ("GitGuardian", "domain", "contains", "gitguardian.com", "GitGuardian"),
    ("Greptile", "domain", "contains", "greptile.com", "Greptile"),
    ("Codeforces", "domain", "contains", "codeforces.com", "Codeforces"),
    ("GNU", "domain", "contains", "gnu.org", "GNU"),
    ("OpenAI", "domain", "contains", "openai.com", "OpenAI"),
    ("Anthropic", "domain", "contains", "anthropic.com", "Anthropic"),
    ("DeepSeek", "domain", "contains", "deepseek.com", "DeepSeek"),
    ("Flashduty", "domain", "contains", "flashduty.com", "Flashduty"),
    ("OpenRouter", "domain", "contains", "openrouter.ai", "OpenRouter"),
    ("Codex", "domain", "contains", "chatgpt.com", "Codex"),
    ("Google", "domain", "contains", "google", "Google"),
    ("Microsoft", "domain", "contains", "microsoft.com", "Microsoft"),
    ("Apple", "domain", "contains", "apple", "Apple"),
    ("小米", "domain", "contains", "xiaomi.com", "小米"),
    ("腾讯", "domain", "contains", "tencent.com", "腾讯"),
    ("Telegram", "domain", "contains", "telegram.org", "Telegram"),
    ("Discord", "domain", "contains", "discord.com", "Discord"),
    ("WhatsApp", "domain", "contains", "whatsapp.com", "WhatsApp"),
    ("X", "domain", "exact", "x.ai", "X"),
    ("X", "domain", "exact", "x.com", "X"),
    ("Reddit", "domain", "contains", "reddit", "Reddit"),
    ("MyFans", "domain", "contains", "myfans.jp", "MyFans"),
    ("Patreon", "domain", "contains", "patreon.com", "Patreon"),
    ("Coursera", "domain", "contains", "coursera.org", "Coursera"),
    ("Artlist", "domain", "contains", "artlist.io", "Artlist"),
    ("Beehiiv", "domain", "contains", "beehiiv.com", "Beehiiv"),
    ("Spotify", "domain", "contains", "spotify.com", "Spotify"),
    ("Steam", "domain", "contains", "steampowered.com", "Steam"),
    ("Firefox", "domain", "contains", "firefox.com", "Firefox"),
    ("Cloudflare", "domain", "contains", "cloudflare.com", "Cloudflare"),
    ("Vercel", "domain", "contains", "vercel.com", "Vercel"),
    ("Render", "domain", "contains", "render.com", "Render"),
    ("Oracle Cloud", "domain", "contains", "oraclecloud.com", "Oracle Cloud"),
    ("RackNerd", "domain", "contains", "racknerd.com", "RackNerd"),
    ("野草云", "domain", "contains", "yecaoyun.com", "野草云"),
    ("Ideaproof", "domain", "contains", "ideaproof.io", "Ideaproof"),
    ("Bright Data", "domain", "contains", "bright", "Bright Data"),
    ("IPRoyal", "domain", "contains", "iproyal.com", "IPRoyal"),
    ("LumiProxy", "domain", "contains", "lumiproxy.com", "LumiProxy"),
    ("ThunderProxy", "domain", "contains", "thunderproxy.com", "ThunderProxy"),
    ("BestProxy", "domain", "contains", "bestproxy.com", "BestProxy"),
    ("CatProxies", "domain", "contains", "catproxies.com", "CatProxies"),
    ("招商银行", "domain", "contains", "cmbchina.com", "招商银行"),
    ("Kraken", "domain", "contains", "kraken.com", "Kraken"),
    ("Cleverbridge", "domain", "contains", "cleverbridge.com", "Cleverbridge"),
    ("giffgaff", "domain", "contains", "giffgaff.com", "giffgaff"),
    ("Vodafone", "domain", "contains", "vodafone.com", "Vodafone"),
    ("PokePay", "domain", "contains", "pokepay.vip", "PokePay"),
    ("智联招聘", "domain", "contains", "zhaopin.cn", "智联招聘"),
)
